path: '/import/c4dm-datasets/MUMS/'

include_dirs:
- DVD 1/BRASS/TRUMPETS/TRUMPET IN C_HARMON MUTE
- DVD 1/BRASS/CORNET
- DVD 2/KEYBOARDS/CELESTA
- DVD 3/WOODWINDS/HISTORICAL WIND INSTRUMENTS/OBOES/OBOE D'AMORE
- DVD 3/WOODWINDS/HISTORICAL WIND INSTRUMENTS/OBOES/BAROQUE OBOE (with flattement) 

blacklist_pattern:
- vibrato
- harmonics